from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('emp_check_in/', views.emp_check_in, name='check_in'),
    path('emp_check_out/', views.emp_check_out, name='check_out'),
    path('assigned_task/', views.assigned_task, name='assigned_task'),
    path('assigned_manager_task/', views.assigned_manager_task, name='assigned_manager_task'),
    path('create-project/', views.create_project, name='create_project'),
    path('edit-project/<str:project_id>/', views.edit_project, name='edit_project'),
    path('show-project-status/<str:project_id>/', views.show_project_status, name='show_project_status'),
    path('delete_project/<str:project_id>/', views.delete_project, name='delete_project'),
    path('create-task/', views.create_task, name='create_task'),
    path('delete_task/<str:task_id>/', views.delete_task, name='delete_task'),
    path('edit-task/<str:task_id>/', views.edit_task, name='edit_task'),
    path('show-my-tasks/', views.show_my_tasks, name='show_my_tasks'),
    path('create-role/', views.create_role, name='create_role'),
    path('delete_role/<str:id>/', views.delete_role, name='delete_role'),
    path('edit_role/<str:id>/', views.edit_role, name='edit_role'),
    path('create_team/', views.create_team, name='create_team'),
    path('delete_team/<str:team_id>/', views.delete_team, name='delete_team'),
    path('edit_team/<str:team_id>/', views.edit_team, name='edit_team'),
    path('view-my-teams/', views.view_my_teams, name='view_my_teams'),
    path('assign-task/<str:user>/', views.assign_task_to_team_member, name='assign_task_to_team'),
    path('show-tasks/<str:user>/', views.show_employee_tasks, name='show_employee_tasks'),
    path('show-assigned-manager-task/', views.show_assigned_manager_task, name='show_assigned_manager_task'),
    path('view-my-emptask/', views.view_my_emptask, name='view_my_emptask'),
    path('delete-emptask/<str:task_name>/', views.delete_emptask, name='delete_emptask'),
    path('project-manager-dashboard/<str:user>/', views.project_manager_dashboard, name='project_manager_dashboard'),
    path('update_project_status/<str:project_id>/', views.update_managerproject_status, name='update_project_status'),
    path('kanban/', views.kanban_dashboard, name='kanban_dashboard'),
    path('update_project_status/', views.update_project_status, name='update_project_status'),
    path('get_projects/', views.get_projects, name='get_projects'),
    path('get_project_data/', views.get_project_data, name='get_project_data'),
    path('upload_document/<str:task_id>/', views.upload_document, name='upload_document'),
    path('upload_document_emp/<str:id>/', views.upload_document_emp, name='upload_document_emp'),
    path('admin/documents/', views.admin_view_documents, name='admin_view_documents'),
    path('show_performance_employee/<str:username>/', views.employee_performance_view, name='show_performance_employee'),
    path('show_performance_manager/<str:username>/', views.manager_performance_view, name='show_performance_manager'),
    path('create_training_program/', views.create_training_program, name='create_training_program'),
    path('training_programs/', views.list_training_programs, name='training_programs'),
    path('training_progress/', views.view_training_progress, name='training_progress'),
    path('enroll_participant/', views.enroll_participant, name='enroll_participant'),
    path('update_program/<str:program_id>/', views.update_program, name='update_program'),
    path('delete_program/<str:program_id>/', views.delete_program, name='delete_program'),
    path('update_progress/<str:program_name>/', views.update_progress, name='update_progress'),
    path('delete_progress/<str:program_name>/', views.delete_progress, name='delete_progress'),
    path('upload_certificate/', views.upload_certificate, name='upload_certificate'),
    path('employee_dashboard_certificates/', views.employee_dashboard_certificates, name='employee_dashboard_certificates'),
    path('manager_dashboard_certificates/', views.manager_dashboard_certificates, name='manager_dashboard_certificates'),
    path('enroll_training_manager/', views.enroll_training_manager, name='enroll_training_manager'),
    path('enroll_training_employee/', views.enroll_training_employee, name='enroll_training_employee'),
    path('enroll_manager/', views.enroll_manager, name='enroll_manager'),
    path('enroll_employee/', views.enroll_employee, name='enroll_employee'),
    path('performance_chart/', views.performance_chart_view, name='performance_chart'),
    path('task_check_in/', views.task_check_in, name='task_check_in'),
    path('task_check_out/', views.task_check_out, name='task_check_out'),
    path('md_create_project/', views.md_create_project, name='md_create_project'),
    path('md_edit_project/<str:project_id>/', views.md_edit_project, name='md_edit_project'),
    path('md_show_project_status/<str:project_id>/', views.md_show_project_status, name='md_show_project_status'),
    path('md_delete_project/<str:project_id>/', views.md_delete_project, name='md_delete_project'),
    path('md_create_task/', views.md_create_task, name='md_create_task'),
    path('md_edit_task/<str:task_id>/', views.md_edit_task, name='md_edit_task'),
    path('md_delete_task/<str:task_id>/', views.md_delete_task, name='md_delete_task'), 
    path('md_create_role/', views.md_create_role, name='md_create_role'),
    path('md_edit_role/<str:id>/', views.md_edit_role, name='md_edit_role'),
    path('md_delete_role/<str:id>/', views.md_delete_role, name='md_delete_role'), 
    path('md_create_team/', views.md_create_team, name='md_create_team'),
    path('md_edit_team/<str:team_id>/', views.md_edit_team, name='md_edit_team'),
    path('md_delete_team/<str:team_id>/', views.md_delete_team, name='md_delete_team'),
    path('md_kanban/', views.md_kanban_dashboard, name='md_kanban_dashboard'),
    path('md_get_projects/', views.md_get_projects, name='md_get_projects'),
    path('md_get_project_data/', views.md_get_project_data, name='md_get_project_data'),
    path('md_admin/documents/', views.md_admin_view_documents, name='md_admin_view_documents'),
    path('md_show_performance_employee/<str:username>/', views.md_employee_performance_view, name='md_show_performance_employee'),
    path('md_show_performance_manager/<str:username>/', views.md_manager_performance_view, name='md_show_performance_manager'),
    path('md_training_programs/', views.md_create_training_program, name='md_create_training_program'),
    path('md_enroll_participant/', views.md_enroll_participant, name='md_enroll_participant'),
    path('md_training_progress/', views.md_view_training_progress, name='md_training_progress'),
    path('md_update_program/<str:program_id>/', views.md_update_program, name='md_update_program'),
    path('md_delete_program/<str:program_id>/', views.md_delete_program, name='md_delete_program'),
    path('md_update_progress/<str:program_name>/', views.md_update_progress, name='md_update_progress'),
    path('md_delete_progress/<str:program_name>/', views.md_delete_progress, name='md_delete_progress'),
    path('md_upload_certificate/', views.md_upload_certificate, name='md_upload_certificate'),
    path('md_performance-chart/<str:user_type>/<int:user_id>/', views.md_performance_chart, name='md_performance_chart'),
    path('md_create_performance_review/', views.md_create_performance_review, name='md_create_performance_review'),
    path('md_performance_review_list/', views.md_performance_review_list, name='md_performance_review_list'),

    # Goal Endpoints
    path('md_create_goal/', views.md_create_goal, name='md_create_goal'),
    path('md_goal_list/', views.md_goal_list, name='md_goal_list'),

    # Feedback Endpoints
    path('md_create_feedback/', views.md_create_feedback, name='md_create_feedback'),
    path('md_feedback_list/', views.md_feedback_list, name='md_feedback_list'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
