# Generated by Django 5.0.6 on 2024-10-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='employee_name',
        ),
    ]
