# Generated by Django 5.0.6 on 2024-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.CharField(choices=[('Aadhar', 'Aadhar Card'), ('PAN', 'PAN Card'), ('Bank', 'Bank Details'), ('Email', 'Employee Email'), ('Payslip', 'Previous Company Payslip'), ('Experience', 'Experience Certificate'), ('Degree', 'Degree Certificate')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
