# Generated by Django 5.0.6 on 2024-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorPayrollNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=40)),
                ('user_id', models.CharField(max_length=30)),
                ('date', models.DateField(default=True)),
                ('time', models.TimeField()),
                ('message', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('email', models.EmailField(blank=True, default=True, max_length=254)),
                ('base_salary', models.CharField(max_length=20)),
                ('net_salary', models.CharField(default='0', max_length=20)),
                ('total_working_hours', models.CharField(default='0', max_length=20)),
                ('overtime_hours', models.CharField(default='0', max_length=20)),
                ('overtime_pay', models.CharField(default='0', max_length=30)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'month')},
            },
        ),
    ]
