# Generated by Django 5.0.6 on 2024-12-24 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('bonus_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_status', models.CharField(blank=True, max_length=20, null=True)),
                ('total_paid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('annual_salary', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20)),
                ('total_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_salary', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
