# Generated by Django 5.0.6 on 2024-12-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('project_manager', models.CharField(max_length=100)),
                ('project_status', models.CharField(default='not_started', max_length=50)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emptask_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=50)),
                ('deadline', models.DateField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('team_project_name', models.CharField(max_length=100)),
                ('emp_taskstatus', models.CharField(default='Not Started', max_length=50)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emptask', to='authentication.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('project_manager', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authentication.manager')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='task_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectmanagement.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEmpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='task_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projectmanagement.employee_task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='authentication.employee')),
                ('employeetask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='projectmanagement.employee_task')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='authentication.manager')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='projectmanagement.task')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100)),
                ('team_task', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='authentication.manager')),
                ('members', models.ManyToManyField(related_name='team_members', to='authentication.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projectmanagement.project')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='authentication.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee_task',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.team'),
        ),
        migrations.CreateModel(
            name='TrainingParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('certification_date', models.DateField()),
                ('certification_file', models.FileField(upload_to='certificates/')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.trainingparticipation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('for_managers', models.BooleanField(default=False)),
                ('for_employees', models.BooleanField(default=True)),
                ('training_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.manager')),
            ],
        ),
        migrations.AddField(
            model_name='trainingparticipation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.trainingprogram'),
        ),
    ]
