# Generated by Django 5.0.6 on 2024-12-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_news_req_todo_requests_ticket'),
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_task',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='employee_task',
            name='team_project_name',
        ),
        migrations.AddField(
            model_name='employee_task',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='emp_taskstatus',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('in review', 'In Review'), ('completed', 'Completed')], default='not started', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.manager'),
        ),
        migrations.AlterField(
            model_name='employee_task',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('in review', 'In Review'), ('completed', 'Completed')], default='not started', max_length=100),
        ),
    ]
